### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by duboisph**

### CODE REVIEW

**Comment by MattiasGees** [comment]
Why not encapsulate the other two modules?

**Comment by duboisph** [comment]
I don't really see why there's a need to split off bucket and user definition, it's never used separately I think.

Therefore we thought to follow the current trend and create this new module around the duply topic, like the other ones that are being created the last weeks. Also documentation in 1 place.

**Comment by MattiasGees** [comment]
What if you use instance profiles to regulate your backups?

**Comment by ringods** [comment]
@MattiasGees OK, if I change to a structure similar to `terraform-loadbalancers` containing different modules representing different setups? I'll name the current setup `bucket_iamuser` then and the case for instance profiles could become another module.

**Comment by MattiasGees** [comment]
why not just write an encapsulation on it?

**Comment by ringods** [comment]
Outcome after discussion in Zoom: `duply_bucket` and `duply_user` will move from repository `terraform-skyscrapers` to `terraform-duply`. Both will then be encapsulated in a module `duply_bucket_iamuser` which describes what is encapsulated.

**Review by SamClinckspoor — APPROVED** [review]

**Review by MattiasGees — APPROVED** [review]

**Pull request merged**
